server:
  port: 8090

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

logstash:
  host: localhost

spring:
  application:
    name: user-server
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: demo
      port: 27017
      host: localhost
      auto-index-creation: true