server:
  port: 8096

spring:
  application:
    name: person-macros-calculation-server

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

logstash:
  host: localhost