FROM openjdk:17

COPY ./build/libs/dish-macros-calculator-server-0.0.1-SNAPSHOT.jar dish-macros-calculator-server-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","dish-macros-calculator-server-0.0.1-SNAPSHOT.jar"]