server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Avokado-an/microservice-config-server.git

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka